### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by daramcq** [ronan-mch/lobbying#3]
Hey, no info in the Readme as to how to set up the project locally. Not a Ruby user, so some guidelines would be appreciated!

**Comment by ronan-mch** [comment]
I wrote that you should load the database using `sqlite3 lobbying.db`, or use sqlitebrowser or whatever you want. I added the ruby scripts for reference; they've been used to pull down and work with the data but shouldn't be needed once the data is in the database. I will write some more scripts to add more columns to the db, but I'm assuming this will be my job.
